In [1]:
import pandas as pd

The IMGT/GENE-DB FASTA header contains 15 fields separated by '|':
1. IMGT/LIGM-DB accession number(s)
2. IMGT gene and allele name
3. species (may be followed by an "_" and the name of the strain, breed or isolate, if defined)
4. IMGT gene and allele functionality
5. exon(s), region name(s), or extracted label(s)
6. start and end positions in the IMGT/LIGM-DB accession number(s)
7. number of nucleotides in the IMGT/LIGM-DB accession number(s)
8. codon start, or 'NR' (not relevant) for non coding labels
9. +n: number of nucleotides (nt) added in 5' compared to the corresponding label extracted from IMGT/LIGM-DB
10. +n or -n: number of nucleotides (nt) added or removed in 3' compared to the corresponding label extracted from IMGT/LIGM-DB
11. +n, -n, and/or nS: number of added, deleted, and/or substituted nucleotides to correct sequencing errors, or 'not corrected' if non corrected sequencing errors
12. number of amino acids (AA): this field indicates that the sequence is in amino acids
13. number of characters in the sequence: nt (or AA)+IMGT gaps=total
14. partial (if it is)
15. reverse complementary (if it is)

In [6]:
columns = [
    "accession number",
    "name",
    "species",
    "functionality",
    "exon/name/label",
    "start end positions",
    "number of nucleotides",
    "codon start",
    "+n",
    "+/-n",
    "error corrections",
    "number of AA",
    "number of char",
    "partial",
    "reverse complementary",
    "FASTA"]
df = pd.DataFrame(columns=columns)

In [7]:
print(len(columns))

16

In [8]:
with open('IMGTGENEDB-ReferenceSequences.fasta-AA-WithoutGaps-F+ORF+inframeP', 'r') as file:
    row = ''
    while True:
        line = file.readline().replace('\n', '')
        if line:
            if line.startswith('>'):
                if row:
                    df.loc[len(df)] = row.split('|')
                row = line[1:]
            else:
                row += line
        else:
            df.loc[len(df)] = row.split('|')
            break

In [9]:
df.head()

,accession number,name,species,functionality,exon/name/label,start end positions,number of nucleotides,codon start,+n,+/-n,error corrections,number of AA,number of char,partial,reverse complementary,FASTA
0,KT723008,IGHA*01,Bos taurus_Holstein,F,CH1,"n,652007..652311",306 nt,1,+1,-1,,102 AA,102+0=102,,,XSETSPSIFPLSLGNNDPAGQVVIGCLVQGFFPSAPLSVTWNQNGD...
1,KT723008,IGHA*01,Bos taurus_Holstein,F,H-CH2,"g,652493..652821",330 nt,1,+1,-1,,110 AA,110+0=110,,,DSSSCCVPNCEPSLSVQPPALEDLLLGSNASLTCTLSGLKSAEGAS...
2,KT723008,IGHA*01,Bos taurus_Holstein,F,CH3-CHS,"g,653011..653402",393 nt,1,+1,,,131 AA,131+0=131,,,GNTFRPQVHLLPPPSEELALNELVTLTCLVRGFSPKEVLVRWLQGN...
3,KT723008,IGHA*01,Bos taurus_Holstein,F,M,"g,655709..655893",186 nt,1,+1,,,62 AA,62+0=62,,,EHQPWLVLDLMQSSPEEDSPEASLWPTTVTLLTLFLLSLFYSTALT...
4,KT723008,IGHD*02,Bos taurus_Holstein,ORF,CH1,"n,525572..525894",324 nt,1,+1,-1,,108 AA,108+0=108,,,XGESHLRVFSLVSCVSSPSDESTVALGCLARDFVPNSVSFSWKFNN...

In [10]:
df.to_csv('IMGT_GENE.csv')